export const API_PATH = {
    auth: {
        login: '/login',
        join: '/user-auth/api/v1/user/register',
        confirm_eamil: '/user-auth/api/v1/user/confirm-email',
        verify_email: '/user-auth/api/v1/user/verify-email',
        get_ip: '/user-auth/api/v1/user/get-ip',
        renew_token: '/user-auth/api/v1/user/renew-token',
        verify_otp: '/user-auth/api/v1/user/verify-otp',
        password_reset: '/user-auth/api/v1/user/password/reset',
        logout: '/user-auth/api/v1/user/logout',
        password_change: 'user-auth/api/v1/user/password/change',
        defer_change: 'user-auth/api/v1/user/password/defer-change',
        ask_user_info: '/user-auth/api/v1/user/ask-user-info',
        // add
        captcha: '/captcha',
        authcode: '/authcode',
    },
    gpss: {
        reviewer: '/user-auth/api/v1/auth/reviewer-search?',
        approver: '/user-auth/api/v1/auth/manager-search?',
        gpss_search: '/adminmgmt/api/v1/search/unified-search',
        gpss_detail: '/adminmgmt/api/v1/search/detail-search',
        gpss_suggestion: '/adminmgmt/api/v1/search/suggest?',
    },
    approval: {
        history_list: '/adminmgmt/api/v1/history/all-histories',
        history_detail: '/adminmgmt/api/v1/history/history/detail',
        history_temp_save_requester: '/adminmgmt/api/v1/request/draft-requester',
        history_temp_save_reviewer: '/adminmgmt/api/v1/request/draft-reviewer',
    },
    permission: {
        role_menu_permission: '/user-auth/api/v1/auth/role-menu-permission',
        role_change_user_list: '/user-auth/api/v1/auth/role-change-user-list',
        target_userId_role: (targetUserId) => `/user-auth/api/v1/auth/${targetUserId}/role`,
        get_role_menu: 'user-auth/api/v1/auth/get-role-menu',
        modify_role_menu: 'user-auth/api/v1/auth/modify-role-menu',
    },
    system: {
        service_regist: '/service-regist',
        service_list: '/service-list',
        service_update: '/service-update',
        service_code: '/service-code',
        ue_regist: '/ue-regist',
        ue_list: '/ue-list',
        ue_update: '/ue-update',
        ue_delete: '/ue-delete',
        loc_trans: '/loc-trans',
        loc_view: '/loc-view',
    },
    user: {
        user_regist: '/user-regist',
        user_dup: '/user-dup',
        user_list: '/user-list',
        user_update: '/user-update',
        user_delete: '/user-delete',
        permission_info: '/permission-info',
        permission_update: '/permission-update',
        user_history: '/user-history',
    },
    service: {
        service_stat: '/service-stat',
        cloud_stat: '/cloud-stat',
        trigger: '/trigger-list',
    },
}
