export const API_PATH = {
    auth: {
        join: '/user-auth/api/v1/user/register',
        confirm_eamil: '/user-auth/api/v1/user/confirm-email',
        verify_email: '/user-auth/api/v1/user/verify-email',
        get_ip: '/user-auth/api/v1/user/get-ip',
        renew_token: '/user-auth/api/v1/user/renew-token',
        verify_otp: '/user-auth/api/v1/user/verify-otp',
        password_reset: '/user-auth/api/v1/user/password/reset',
        logout: '/user-auth/api/v1/user/logout',
        password_change: 'user-auth/api/v1/user/password/change',
        defer_change: 'user-auth/api/v1/user/password/defer-change',
        // add
        // captcha: '/captcha',
        // authcode: '/authcode',
        dummyToken: '/api/dummy',
        smscode: '/api/sms',
        captcha: '/api/captcha',
        login: '/api/login',
        logout: '/api/logout',
        ask_user_permission: '/api/users/authority/menu',
    },
    system: {
        service_regist: '/api/system/service/regist',
        service_list: '/api/system/service',
        service_update: '/api/system/service/modify',
        service_code: '/api/system/service/check',
        ue_regist: '/api/system/ue/regist',
        ue_list: '/api-system-ue-list',
        ue_update: '/api/system/ue/modify',
        ue_delete: '/api-system-ue-delete',
        loc_trans: '/loc-trans',
        loc_view: '/loc-view',
    },
    user: {
        user_regist: '/user-regist',
        user_dup: '/user-dup',
        user_list: '/user-list',
        user_update: '/user-update',
        user_delete: '/user-delete',
        permission_info: '/permission-info',
        permission_update: '/permission-update',
        user_history: '/user-history',
    },
    facility: {
        wifi_search: '/facility-wifi-search',
        wifi_regist: '/facility-wifi-regist',
        wifi_delete: '/facility-wifi-delete',
        wifi_update: '/facility-wifi-update',
        bts_search: '/facility-bts-search',
        sync_history: '/facility-sync-history',
    },
    service: {
        service_history_detail: '/service-history-detail',
        service_history: '/service-history',
        service_stat: '/service-stat',
        cloud_stat: '/cloud-stat',
        trigger: '/trigger-list',
    },
}
